# - Try to find pag suite
# Once done this will define
#  PAGSUITE_FOUND - System has LibXml2
#  PAGSUITE_INCLUDE_DIRS - The LibXml2 include directories
#  PAGSUITE_LIBRARIES - The libraries needed to use LibXml2
#  PAGSUITE_DEFINITIONS - Compiler switches required for using LibXml2



FIND_LIBRARY( RPAG_LIB NAMES rpag )
FIND_PATH( RPAG_INCLUDE_DIR NAMES rpag/rpag.h )
IF( RPAG_LIB AND RPAG_INCLUDE_DIR)
	SET(RPAG_FOUND true)
	Message(STATUS "Found rpag: ${RPAG_LIB} (${RPAG_INCLUDE_DIR})")
	mark_as_advanced( RPAG_FOUND RPAG_LIB RPAG_INCLUDE_DIR )
ELSE( RPAG_LIB AND RPAG_INCLUDE_DIR)
	Message(STATUS "Could not find rpag (RPAG_LIB=${RPAG_LIB}, RPAG_INCLUDE_DIR=${RPAG_INCLUDE_DIR})")
ENDIF(RPAG_LIB AND RPAG_INCLUDE_DIR )

FIND_LIBRARY( PAGLIB_LIB NAMES pag_lib )
FIND_PATH( PAGLIB_INCLUDE_DIR NAMES pag_lib/adder_graph.h )
IF( PAGLIB_LIB AND PAGLIB_INCLUDE_DIR )
	SET(PAGLIB_FOUND true)
	Message(STATUS "Found paglib: ${PAGLIB_LIB} (${PAGLIB_INCLUDE_DIR})")
	mark_as_advanced( PAGLIB_FOUND PAGLIB_LIB PAGLIB_INCLUDE_DIR )
ELSE( PAGLIB_LIB AND PAGLIB_INCLUDE_DIR )
	Message(STATUS "Could not find paglib (PAGLIB_LIB=${PAGLIB_LIB}, PAGLIB_INCLUDE_DIR=${PAGLIB_INCLUDE_DIR})")
ENDIF(PAGLIB_LIB AND PAGLIB_INCLUDE_DIR )

FIND_LIBRARY( COPA_LIB NAMES copa )
FIND_PATH( COPA_INCLUDE_DIR NAMES copa/copa.h )
#FIND_PATH( COPA_INCLUDE_DIR NAMES copa.h )

#MESSAGE(STATUS "DEBUG: CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}")
#MESSAGE(STATUS "DEBUG: COPA_LIB: ${COPA_LIB}")
#MESSAGE(STATUS "DEBUG: COPA_INCLUDE_DIR: ${COPA_INCLUDE_DIR}")


IF( COPA_LIB AND COPA_INCLUDE_DIR )
	SET(COPA_FOUND true)
	Message(STATUS "Found copa: ${COPA_LIB} (${COPA_INCLUDE_DIR})")
	mark_as_advanced( COPA_FOUND COPA_LIB COPA_INCLUDE_DIR )
ELSE( COPA_LIB AND COPA_INCLUDE_DIR )
	Message(STATUS "Could not find copa (COPA_LIB=${COPA_LIB}, COPA_INCLUDE_DIR=${COPA_INCLUDE_DIR})")
ENDIF(COPA_LIB AND COPA_INCLUDE_DIR)

IF( RPAG_FOUND AND PAGLIB_FOUND AND COPA_FOUND )
	set(PAGSUITE_FOUND true)
	set(PAGSUITE_LIBRARIES ${RPAG_LIB} ${PAGLIB_LIB} ${COPA_LIB} )
	set(PAGSUITE_INCLUDE_DIRS ${RPAG_INCLUDE_DIR} ${PAGLIB_INCLUDE_DIR} ${COPA_INCLUDE_DIR} )
ENDIF( RPAG_FOUND AND PAGLIB_FOUND AND COPA_FOUND )


